version: '3.7'

services:
  boilerplate-apollo:
    container_name: boilerplate-apollo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '$PORT:$PORT'
    env_file: .env
    restart: always
