version: '3.7'

services:
  rune_holder:
    container_name: rune_holder
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '$PORT:$PORT'
    env_file: .env
    restart: always
